#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &
nitrogen --restore &
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5

bspc config border_width        0
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color     "#d8dee9"
bspc config normal_border_color      "#202A25"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^3' follow=false
