#!/bin/sh

#pgrep || picom &
#pgrep bspswallow || bspswallow &
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5

bspc config border_width        0
bspc config window_gap          5
#bspc rule -a alacritty stacking=on
#bspc rule -a * state=stacking

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color     "#ffffff"
bspc config normal_border_color      "#434C5E"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^3' follow=false

